baseURL = 'https://Kingtuo123.com/'
title = "Nobody's Blog"
disableKinds = ["taxonomy", "term", "section"]

[params]
	defaultTheme = "light"
	headerTitle = "夜不能寐"

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
	[markup.tableOfContents]
		endLevel = 4
		ordered = false
		startLevel = 2
	[markup.highlight]
		noClasses = false
